name: C:\Users\M042266\.conda\envs\product_reviews_australia
dependencies:
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- beautifulsoup4=4.4.1=py27_0
- colorama=0.3.7=py27_0
- configparser=3.5.0=py27_0
- decorator=4.0.10=py27_0
- entrypoints=0.2.2=py27_0
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- ipykernel=4.3.1=py27_0
- ipython=5.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_1
- jsonschema=2.5.1=py27_0
- jupyter_client=4.3.0=py27_0
- jupyter_core=4.1.0=py27_0
- markupsafe=0.23=py27_2
- mistune=0.7.2=py27_0
- mkl=11.3.3=1
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- nltk=3.2.1=py27_0
- notebook=4.2.2=py27_0
- numpy=1.11.1=py27_1
- pandas=0.18.1=np111py27_0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pickleshare=0.7.3=py27_0
- pip=8.1.2=py27_0
- prompt_toolkit=1.0.3=py27_0
- pygments=2.1.3=py27_0
- python=2.7.12=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- pyzmq=15.3.0=py27_0
- scikit-learn=0.17.1=np111py27_1
- scipy=0.18.0=np111py27_0
- setuptools=25.1.6=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- ssl_match_hostname=3.4.0.2=py27_1
- tornado=4.4.1=py27_0
- traitlets=4.2.2=py27_0
- vs2008_runtime=9.00.30729.1=2
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- win_unicode_console=0.5=py27_0
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-core==4.1.0
  - prompt-toolkit==1.0.3
  - seaborn==0.7.1
  - win-unicode-console==0.5

